// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Data;

#nullable disable

namespace WebApp.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Model.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be9b63ff-af37-4010-8fe2-ad534fd5003e"),
                            Code = "AES"
                        },
                        new
                        {
                            Id = new Guid("688f56ea-46c1-436a-ae9e-8c2c55c2c0db"),
                            Code = "YXX"
                        },
                        new
                        {
                            Id = new Guid("e242c9ec-00c0-468d-a2f4-b5272c72d0c8"),
                            Code = "ABZ"
                        },
                        new
                        {
                            Id = new Guid("02a94dde-5c29-4e28-bfdc-7ee4d2c34591"),
                            Code = "ABJ"
                        },
                        new
                        {
                            Id = new Guid("fabf35b2-d7f2-424f-9006-e15ed821928b"),
                            Code = "AUH"
                        },
                        new
                        {
                            Id = new Guid("9933caf8-8a15-4a70-a487-d9cf9c7806e8"),
                            Code = "ACA"
                        },
                        new
                        {
                            Id = new Guid("519c5c35-2d60-4cdc-a331-e705ef305d22"),
                            Code = "ADA"
                        },
                        new
                        {
                            Id = new Guid("a7c76537-5b8c-4369-8a76-3761cf799ab1"),
                            Code = "ADL"
                        },
                        new
                        {
                            Id = new Guid("9d4c68fb-9afb-4dbb-bcdc-aa56b6b440cf"),
                            Code = "ADF"
                        },
                        new
                        {
                            Id = new Guid("60b4fe28-d1fe-4c1a-ad41-ea83fd42c4f9"),
                            Code = "GUM"
                        },
                        new
                        {
                            Id = new Guid("30536cf8-5a8d-46ee-9c23-44d732fbf28e"),
                            Code = "AGU"
                        },
                        new
                        {
                            Id = new Guid("1ec5bb10-58b3-48d5-87e0-5152eb997b14"),
                            Code = "AMD"
                        },
                        new
                        {
                            Id = new Guid("ccf71d15-696f-474b-89e4-375596392e69"),
                            Code = "AXT"
                        },
                        new
                        {
                            Id = new Guid("37f46204-b0de-4e93-a74f-f66bc055b2a9"),
                            Code = "ALS"
                        },
                        new
                        {
                            Id = new Guid("b95c8e02-ae49-4b40-8ae8-7c4a6bf82af4"),
                            Code = "ALB"
                        },
                        new
                        {
                            Id = new Guid("cfd78e93-f5c7-46d3-ad52-31c86ae3bf87"),
                            Code = "ABQ"
                        },
                        new
                        {
                            Id = new Guid("feaec228-b41a-4cac-9155-34474d4ed1c2"),
                            Code = "ALY"
                        },
                        new
                        {
                            Id = new Guid("0cc51007-5187-414b-b55b-3af6023a54e1"),
                            Code = "AHO"
                        },
                        new
                        {
                            Id = new Guid("52cda36b-8c4f-40ea-bd2a-7409124101aa"),
                            Code = "ALC"
                        },
                        new
                        {
                            Id = new Guid("6ddaa335-1f81-428e-a3bb-9819b34189b2"),
                            Code = "NSB"
                        },
                        new
                        {
                            Id = new Guid("0be95ac0-a3e3-43e5-b305-48bf59e4f605"),
                            Code = "AIA"
                        },
                        new
                        {
                            Id = new Guid("44b00cd2-916a-43b0-8c0b-fd93de913ec7"),
                            Code = "LEI"
                        },
                        new
                        {
                            Id = new Guid("31620eb9-7a92-4402-aeae-2858dd5942e6"),
                            Code = "APN"
                        },
                        new
                        {
                            Id = new Guid("887bd4eb-627e-458e-ade1-7f36d87718c4"),
                            Code = "ACH"
                        },
                        new
                        {
                            Id = new Guid("7a20b5c5-5d8b-4cc4-b008-d34a7d98ff75"),
                            Code = "ZAZ"
                        },
                        new
                        {
                            Id = new Guid("8722b824-faf6-4c93-96a9-d41d146fe95f"),
                            Code = "ZAM"
                        },
                        new
                        {
                            Id = new Guid("ce510c8c-f4b8-4db2-b77b-45f01d3076c1"),
                            Code = "ZAD"
                        },
                        new
                        {
                            Id = new Guid("c4654592-554a-4cd9-adce-3093956f6354"),
                            Code = "YZF"
                        },
                        new
                        {
                            Id = new Guid("5a559560-3645-4432-b7d0-7c5a6878d0b1"),
                            Code = "EVN"
                        },
                        new
                        {
                            Id = new Guid("ae84a5ae-358e-4b04-aa3f-324372ffa3a5"),
                            Code = "YUM"
                        },
                        new
                        {
                            Id = new Guid("3451b36e-32af-4a41-9a05-3b730c8586ec"),
                            Code = "YNY"
                        },
                        new
                        {
                            Id = new Guid("ef9a1269-80a3-43c9-a6e8-0f902a60e402"),
                            Code = "YNT"
                        },
                        new
                        {
                            Id = new Guid("dbc624a0-b399-45b6-a4ec-575ec6652e44"),
                            Code = "YAO"
                        },
                        new
                        {
                            Id = new Guid("48c24aa5-ed36-4e4e-89bc-07dd5fc5daec"),
                            Code = "SJC"
                        },
                        new
                        {
                            Id = new Guid("46fa70fb-d1c8-4569-a6cd-ed2c5cb0598a"),
                            Code = "SBP"
                        },
                        new
                        {
                            Id = new Guid("9c6c1491-e4da-462c-ad34-a046c2f186cc"),
                            Code = "SAL"
                        },
                        new
                        {
                            Id = new Guid("3456f7a7-3308-40d5-a3de-ce1d6d07aa6a"),
                            Code = "HRK"
                        },
                        new
                        {
                            Id = new Guid("be114477-ab16-43e6-8160-b44780e8d7d4"),
                            Code = "KKC"
                        },
                        new
                        {
                            Id = new Guid("2f1971f2-1857-4210-a3f8-d3f183567686"),
                            Code = "KTN"
                        },
                        new
                        {
                            Id = new Guid("2e423506-11cb-4f97-886a-77ada95db630"),
                            Code = "YLW"
                        },
                        new
                        {
                            Id = new Guid("01e570bb-0ff6-4ff7-a7a0-c593d4fb384c"),
                            Code = "ENA"
                        },
                        new
                        {
                            Id = new Guid("af0ead33-269a-43b1-9b4f-ecb6bc0a3f88"),
                            Code = "YQK"
                        },
                        new
                        {
                            Id = new Guid("5101b4c9-0306-4033-801d-1575dcc305ea"),
                            Code = "AZO"
                        },
                        new
                        {
                            Id = new Guid("e1098f36-f69d-4b12-9230-8a9818911fe4"),
                            Code = "KGI"
                        },
                        new
                        {
                            Id = new Guid("78bd612f-e246-4649-84f3-436725c13e5c"),
                            Code = "KGD"
                        });
                });

            modelBuilder.Entity("WebApp.Model.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WebApp.Model.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArrivalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("DepartureId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("WebApp.Model.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("WebApp.Model.Booking", b =>
                {
                    b.HasOne("WebApp.Model.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("WebApp.Model.Flight", b =>
                {
                    b.HasOne("WebApp.Model.Airport", "ArrivalAirport")
                        .WithMany("ArrivalFlights")
                        .HasForeignKey("ArrivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Model.Airport", "DepartureAirport")
                        .WithMany("DepartureFlights")
                        .HasForeignKey("DepartureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("WebApp.Model.Passenger", b =>
                {
                    b.HasOne("WebApp.Model.Booking", null)
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("WebApp.Model.Airport", b =>
                {
                    b.Navigation("ArrivalFlights");

                    b.Navigation("DepartureFlights");
                });

            modelBuilder.Entity("WebApp.Model.Booking", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
